// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'deeprails-mcp/filtering';
import { Metadata, asTextContentResult } from 'deeprails-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Deeprails from 'deeprails';

export const metadata: Metadata = {
  resource: 'defend',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/defend/{workflow_id}/events',
};

export const tool: Tool = {
  name: 'submit_event_defend',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nSubmit a model input and output pair to a workflow for evaluation.\n\n# Response Schema\n```json\n{\n  $ref: '#/$defs/workflow_event_response',\n  $defs: {\n    workflow_event_response: {\n      type: 'object',\n      description: 'Response payload for workflow event operations.',\n      properties: {\n        event_id: {\n          type: 'string',\n          description: 'A unique workflow event ID.'\n        },\n        workflow_id: {\n          type: 'string',\n          description: 'Workflow ID associated with the event.'\n        },\n        attempt_number: {\n          type: 'integer',\n          description: 'Count of improvement attempts for the event.  If greater than one then all previous improvement attempts failed.'\n        },\n        evaluation_id: {\n          type: 'string',\n          description: 'A unique evaluation ID associated with this event.  Every event has one or more evaluation attempts.'\n        },\n        filtered: {\n          type: 'boolean',\n          description: '`False` if evaluation passed all of the guardrail metrics, `True` if evaluation failed any of the guardrail metrics.'\n        }\n      },\n      required: [        'event_id',\n        'workflow_id'\n      ]\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      workflow_id: {
        type: 'string',
      },
      model_input: {
        type: 'object',
        description:
          'A dictionary of inputs sent to the LLM to generate output.  This must contain a `user_prompt` field and an optional `context` field.  Additional properties are allowed.\n',
        properties: {
          user_prompt: {
            type: 'string',
          },
          context: {
            type: 'string',
          },
        },
        required: ['user_prompt'],
      },
      model_output: {
        type: 'string',
        description: 'Output generated by the LLM to be evaluated.',
      },
      model_used: {
        type: 'string',
        description: 'Model ID used to generate the output, like `gpt-4o` or `o3`.',
      },
      nametag: {
        type: 'string',
        description: 'An optional, user-defined tag for the event.',
      },
      run_mode: {
        type: 'string',
        description:
          'Run mode for the workflow event.  The run mode allows the user to optimize for speed, accuracy, and cost by determining which models are used to evaluate the event.  Available run modes include `precision_plus`, `precision`, `smart`, and `economy`.  Defaults to `smart`.',
        enum: ['precision_plus', 'precision', 'smart', 'economy'],
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['workflow_id', 'model_input', 'model_output', 'model_used', 'nametag', 'run_mode'],
  },
  annotations: {},
};

export const handler = async (client: Deeprails, args: Record<string, unknown> | undefined) => {
  const { workflow_id, jq_filter, ...body } = args as any;
  return asTextContentResult(
    await maybeFilter(jq_filter, await client.defend.submitEvent(workflow_id, body)),
  );
};

export default { metadata, tool, handler };
